### ISSUE TITLE
Test case for 2^20

### ISSUE THREAD

**Issue by drogalis** [joadnacer/atomic_queues#1]
I get a seg fault when benchmarking a queue size of 2^20.

**Comment by joadnacer** [comment]
Thanks for pointing this out - issue is that the compile-time known sized queue uses a stack-allocated array, which at 2^20 size is too large for your system's stack size limits. I'll probably just revert this to using a heap-allocated array which I think makes more sense anyway. Will look at this tomorrow.

In the meanwhile you can either using the runtime-provided size queue (don't specify size in template params, just in constructor), or if on linux you can set `ulimit -s unlimited` to increase max stack size.

**Comment by joadnacer** [comment]
Fixed in 0ea0c3b01542bdc953c27867df60e7348c7dbccc
